packages:
  - frontend
  - backend

allowedBuilds: '@swc/core esbuild better-sqlite3'

ignoredBuiltDependencies:
  - core-js-pure
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
